name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i
      - run: cd projects/banner-generator && npm i
      - run: cd projects/amp && npm i
      - run: npm run build:design
      - run: npm run build:shortcodes
      - run: npm run build:prod
      - run: npm run scully:ci
