name: Firebase deploy

on:
  push:
    branches:
      - master
      - release/*

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm ci
      - run: cd projects/banner-generator && npm ci
      - run: cd projects/amp && npm ci
      - run: npm run build:shortcodes
      - run: npm run build:prod
      - run: npm run scully:ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOTIZ_DEV }}'
          channelId: live
          projectId: notiz-dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
